### ISSUE TITLE
Support for healthcheck endpoint

### ISSUE THREAD

**Issue by MichaelDeBoey** [fly-apps/dockerfile-node#42]
Both Indie & Blues Remix stack have an `/healthcheck` endpoint defined in their `fly.toml`, so it would be nice if we somehow supported this as well

Once that's done, I think Indie stack can be changed to fully use this package instead of needing `.dockerignore`, `Dockerfile`, `fly.toml` & `start.sh` in the repo itself (which will all be outdated quickly and probably already are)

**Comment by rubys** [comment]
released: flyctl v0.1.68 and @flydotio/dockerfile@0.4.1 contain these changes.
