### ISSUE TITLE
bunx dockerfile not working

### ISSUE THREAD

**Issue by ianwalter** [fly-apps/dockerfile-node#53]
When I run
```
bunx dockerfile
```
I get
```
error: could not determine executable to run for package dockerfile
```

Running Bun 1.0.15.

**Comment by rubys** [comment]
Try:

```
bunx @flydotio/dockerfile
```

**Comment by ianwalter** [comment]
Oh ok, thanks, so
```
bunx @flydotio/dockerfile
```
worked but it created a Dockerfile for a Node.js app that uses npm. I assumed it would know to create a Bun Dockerfile if I used bunx.

**Comment by ianwalter** [comment]
Ah, maybe because it's a Next.js app it got overridden. I guess I'll just try to copy over a Bun Dockerfile example instead.
